@startuml

Class Alumno {
    -nombre: String
    -legajo: String
    -materiasAprobadas: List<Materia>
    +tieneCorrelativasAprobadas(): boolean
}

Class Materia {
    -nombre: String
    -codigo: String
    -materiasCorrelativas: List<Materia>
}

Class Inscripcion {
    -alumno: Alumno
    -fecha: Date
    +aprobada(materia: Materia): boolean
}

Alumno --* Inscripcion
Materia --* Inscripcion
Materia --> Materia : "*"
Alumno --> Materia: "*"


@enduml